version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
